name: usmle-static
static_sites:
  - name: usmle-static
    github:
      repo: Imloooser/usmle-static
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: /build
    environment_slug: node-js
    catchall_document: index.html
